Feature/ui improvements
DynamicGravitySystems/DGP pull request #83
Opened 2018-08-24 15:41 UTC by bradyzp

UI Improvements Branch
================
The UI Improvements branch addresses various quality-of-life improvements in the user interface.
- Adds support for storing user settings, better tracking of recent projects, restores main-window state to last known state when launching.
- Implements more intuitive plotting controls for the segment selection plot
- Redesigns the workspace/tab-interface to be more extensible in the future, also adds state save/restore functionality so that individual tabs can load to their last state (i.e. plot what the user had plotted when the tab was closed)
- Adds new Icons and cleans up the resource file. New icons are sourced from [Material.io](https://material.io/tools/icons) which provides open-source icon files with a uniform appearance.
- Adds a documentation launcher action to the application, taking user directly to the DGP docs page on read-the-docs.
- Add initial support to link gravimeter/sensor configuration to specific data-set, w/ visual display in the project tree.

Related Issues
---------------
Closes #82

2018-08-26 14:20 UTC, cbertinato requested changes

2018-08-26 14:20 UTC, cbertinato commented on dgp/gui/settings.py
> +        path = Path(self._settings.value(SettingsKey.LastProjectPath(), None))
`Path` doesn't take `None` as an argument.  Testing without any prior projects raises an exception.

2018-08-26 14:27 UTC, cbertinato commented
Also, a couple of issues that came up in QA testing:
- The new splash screen does not disappear for me when the recent project dialog comes up. 
<img width="1680" alt="screen shot 2018-08-26 at 10 07 30 am" src="https://user-images.githubusercontent.com/20772838/44629202-ce95cb00-a919-11e8-9322-fc82b72ce1a2.png">

- In the project tree, if no datasets have been loaded for a flight, and if I double-click 'No Data', then an exception is raised:

```
Traceback (most recent call last):
  File "/Users/cbertinato/Documents/Git/DGP/dgp/gui/views/project_tree_view.py", line 78, in _on_double_click
    self.model().item_activated(index)
  File "/Users/cbertinato/Documents/Git/DGP/dgp/core/controllers/project_treemodel.py", line 127, in item_activated
    self.tabOpenRequested.emit(item.uid, item)
  File "/Users/cbertinato/Documents/Git/DGP/dgp/core/controllers/datafile_controller.py", line 32, in uid
    return self._datafile.uid
AttributeError: 'NoneType' object has no attribute 'uid'
```
<img width="289" alt="screen shot 2018-08-26 at 10 11 23 am" src="https://user-images.githubusercontent.com/20772838/44629234-292f2700-a91a-11e8-9be5-83a1526a47b8.png">

2018-08-26 14:31 UTC, cbertinato commented
Before adding a data to a dataset I had changed the name of the dataset from the default value.  Then proceeded to add a trajectory.  The old name of the dataset appeared in the dialog.  The import still went through with no issue.
<img width="1119" alt="screen shot 2018-08-26 at 10 28 59 am" src="https://user-images.githubusercontent.com/20772838/44629306-3862a480-a91b-11e8-991d-2a42db9948ab.png">

2018-08-26 14:41 UTC, cbertinato commented
When I minimize the windows (in Mac OSX), and then maximize, then the project tree side bar is toggled off closed.  I can bring it back with the toggle button on top.

2018-08-26 14:49 UTC, cbertinato commented
Also, I can't seem to get the fields from the gravity data to appear in channels boxes on the right of the plots.  The issue appears also to happen for trajectory, but at some point the lat, lon, and height fields did appear, though I don't recall what series of actions I made for that to happen.

2018-08-26 18:06 UTC, bradyzp commented
Hey Chris, thanks for doing some QC and reviewing!

I've pushed up a change set which should resolve the Path issue in settings.py, the exception caused by trying to activate/double-click empty DataFiles, and the issue where the project tree/dock is being hidden after minimizing the window. Also the splash screen visibility issue should have been resolved.

The issue you point out where the DataSet name is not being updated in the import dialog, and the issue where you're not seeing the data channels appear are sort of related I think.
- The DataSet name isn't being updated correctly because the DataSetController is being cloned for display in the import dialog. (And the clone isn't being updated yet)
- Currently if you have a DataSet tab (with the plots) open, and then import a datafile into that dataset, there is no notification to the tab that new data has become available. If you close and reopen the tab you should see the channels.

Both of these issues are sort of related, in that there needs to be some sort of communication between the controllers and 1. any clones that they have, and 2. any UI items such as Tabs that their state has changed.
I've started working on this in a separate branch as I didn't want to pollute this one with too many changes, but basically my plan is to create a standard interface for all controllers which enables them to track (by weak-reference) any clones or references to themselves, and can then notify any referent objects of a state change.

2018-08-27 00:02 UTC, cbertinato approved these changes

2018-08-27 01:48 UTC, merged